### ISSUE TITLE
ガザ地区のOpenStreetMapのデータをgeojsonとしてDeployするべきか？

### ISSUE THREAD

**Issue by yuiseki** [hfu/gs#6]
## What

- ガザ地区の、病院と学校とUNRWAの施設くらいは、比較的静的な地理空間情報のはずである
- Overpass API経由でOpenStreetMapのデータをexportしてgeojson形式でDeployするべきかを検討したい

## Why

- HDXにHOTOSMがOpenStreetMapのデータを投入しているが、 `Updated 1 September 2022` となっていて、古すぎる
  - [HOTOSM State of Palestine Education Facilities (OpenStreetMap Export)](https://data.humdata.org/dataset/hotosm_pse_education_facilities)
  - [HOTOSM State of Palestine Health Facilities (OpenStreetMap Export)](https://data.humdata.org/dataset/hotosm_pse_health_facilities)
  - これよりはマシなデータを作れるはずである

**Comment by hfu** [comment]
いいですね！やってみることにしましょうか。
